### ISSUE TITLE
issue #174

### ISSUE THREAD

**Issue by MarkAsRead** [evancohen/smart-mirror#209]
Hi,

The above mentioned ticket was closed assuming a fix, however I still have the problem.

Did a clean install today and sill run into the problem again.

See log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart smart-mirror@0.0.1
6 info start smart-mirror@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info smart-mirror@0.0.1 Failed to exec start script
9 verbose stack Error: smart-mirror@0.0.1 start: `electron main.js `
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/np$
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/np$
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_proc$
10 verbose pkgid smart-mirror@0.0.1
11 verbose cwd /home/pi/smart-mirror
12 error Linux 4.1.19-v7+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error smart-mirror@0.0.1 start: `electron main.js `
17 error Exit status 1
18 error Failed at the smart-mirror@0.0.1 start script 'electron main.js '.
18 error This is most likely a problem with the smart-mirror package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron main.js
18 error You can get their info via:
18 error     npm owner ls smart-mirror
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Hope you can help

**Comment by MarkAsRead** [comment]
Turns out this error happens when I run from SSH. Can be closed
