### ISSUE TITLE
[31mUnhandled rejection StatusCodeError: 404 - {"statusCode":404,"message":"Resource not found"}  error

### ISSUE THREAD

**Issue by Cminjun** [evancohen/smart-mirror#675]
i added face_detection(cognitive-services) 

```
const cognitiveServices = require('cognitive-services');
		const face =  cognitiveServices.face({
			   API_KEY: myApiKey
		})
		
		const parameters = {
			 returnFaceId: "true",
			 returnFaceLandmarks: "false",
			 returnFaceAttributes:"age, gender"
		};
		const body = {
			 "url": faceUrl
		};


	face.detect({
        parameters,
        body
    })
    .then((response) => {
        console.log('Got response', response);
    })
    .catch((err) => {
        console.error('Encountered error making request:', err);
    });

```
but I get this error.
```

/home/pi/smart-mirror/node_modules/request-promise/node_modules/bluebird/js/release/debuggability.js:870 [31mUnhandled rejection StatusCodeError: 404 - {"statusCode":404,"message":"Resource not found"}
    at new StatusCodeError (/home/pi/smart-mirror/node_modules/request-promise/lib/errors.js:32:15)
    at Request.RP$callback [as _callback] (/home/pi/smart-mirror/node_modules/request-promise/lib/rp.js:77:29)
    at Request.self.callback (/home/pi/smart-mirror/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/smart-mirror/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/smart-mirror/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)[0m

```

**Comment by evancohen** [comment]
I'm not really familiar with the `request-promise` library, but you might want to take a look at this issue that's really similar [request/request-promise#168](https://github.com/request/request-promise/issues/168#issuecomment-263015147).

**Comment by sdetweil** [comment]
closing, no response
