### ISSUE TITLE
a problem with electron

### ISSUE THREAD

**Issue by VH-Tech** [evancohen/smart-mirror#737]
Hi,
I just found about this cool project.
but have the following error message after doing "npm start"
> smart-mirror@0.0.17 start /home/pi/smart-mirror
> electron main.js

/home/pi/smart-mirror/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/pi/smart-mirror/node_modules/electron/index.js:9:9)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/pi/smart-mirror/node_modules/electron/cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smart-mirror@0.0.17 start: `electron main.js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.17 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-05-24T13_54_40_523Z-debug.log

the log: 
[2018-05-24T13_54_40_523Z-debug.log](https://github.com/evancohen/smart-mirror/files/2035678/2018-05-24T13_54_40_523Z-debug.log)
 plz help i am a newbie

**Comment by evancohen** [comment]
Looks like electron didn't install correctly. This should help:
```
cd ~/smart-mirror
rm -r node_modules/electron
npm install
```

**Comment by VH-Tech** [comment]
hi
 I tried this but it didnt respond after this : -
> electron@1.7.14 postinstall /home/pi/smart-mirror/node_modules/electron
> node install.js

and after I did ctrl +c. I got this and did npm install again it showed me : -
> smart-mirror@0.0.17 install /home/pi/smart-mirror
> bower install

up to date in 45.647s

but on doing npm start I got the same error as I reported

**Comment by evancohen** [comment]
This should now be fixed as of `v0.0.19`.
