### ISSUE TITLE
NPM Start Issue

### ISSUE THREAD

**Issue by eusiddiq** [evancohen/smart-mirror#741]
**After NPM install, when I run "npm start", I get the following error:**

```
npm start

> smart-mirror@0.0.17 start /home/eusiddiq/smart-mirror
> electron main.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smart-mirror@0.0.17 start: `electron main.js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-mirror@0.0.17 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eusiddiq/.npm/_logs/2018-06-03T23_52_50_197Z-debug.log
```

**Here is the debug.log:**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle smart-mirror@0.0.17~prestart: smart-mirror@0.0.17
6 info lifecycle smart-mirror@0.0.17~start: smart-mirror@0.0.17
7 verbose lifecycle smart-mirror@0.0.17~start: unsafe-perm in lifecycle true
8 verbose lifecycle smart-mirror@0.0.17~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/eusiddiq/smart-mirror/node_modules/.bin:/home/$9 verbose lifecycle smart-mirror@0.0.17~start: CWD: /home/eusiddiq/smart-mirror
10 silly lifecycle smart-mirror@0.0.17~start: Args: [ '-c', 'electron main.js ' ]
11 silly lifecycle smart-mirror@0.0.17~start: Returned: code: 1  signal: null
12 info lifecycle smart-mirror@0.0.17~start: Failed to exec start script
13 verbose stack Error: smart-mirror@0.0.17 start: `electron main.js `
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid smart-mirror@0.0.17
15 verbose cwd /home/eusiddiq/smart-mirror
16 verbose Linux 4.4.0-43-Microsoft
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error smart-mirror@0.0.17 start: `electron main.js `
22 error Exit status 1
23 error Failed at the smart-mirror@0.0.17 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Everything installed perfectly, no errors, I've tried re-installing electron/node modules using npm install multiple times. Installing electron globally. No success so far with anything.**

**Here is the npm install log:**

```
npm install

> snowboy@1.3.1 install /home/eusiddiq/smart-mirror/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

[snowboy] Success: "/home/eusiddiq/smart-mirror/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-x64/snowboy.node" is installed via remote

> grpc@1.12.2 install /home/eusiddiq/smart-mirror/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/home/eusiddiq/smart-mirror/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote

> protobufjs@6.8.6 postinstall /home/eusiddiq/smart-mirror/node_modules/protobufjs
> node scripts/postinstall


> electron@1.7.15 postinstall /home/eusiddiq/smart-mirror/node_modules/electron
> node install.js


> smart-mirror@0.0.17 install /home/eusiddiq/smart-mirror
> bower install

bower skycons#*             not-cached https://github.com/darkskyapp/skycons.git#*
bower skycons#*                resolve https://github.com/darkskyapp/skycons.git#*
bower angular-i18n#1.5.0        cached https://github.com/angular/bower-angular-i18n.git#1.5.0
bower angular-i18n#1.5.0      validate 1.5.0 against https://github.com/angular/bower-angular-i18n.git#1.5.0
bower angular-translate#2.11.0  cached https://github.com/PascalPrecht/bower-angular-translate.git#2.11.0
bower angular-translate#2.11.0         validate 2.11.0 against https://github.com/PascalPrecht/bower-angular-translate.git#2.11.0
bower moment#2.10.6                      cached https://github.com/moment/moment.git#2.10.6
bower moment#2.10.6                    validate 2.10.6 against https://github.com/moment/moment.git#2.10.6
bower angular#^1.5.0                     cached https://github.com/angular/bower-angular.git#1.7.0
bower angular#^1.5.0                   validate 1.7.0 against https://github.com/angular/bower-angular.git#^1.5.0
bower rrule#2.1.0                        cached https://github.com/jkbr/rrule.git#2.1.0
bower rrule#2.1.0                      validate 2.1.0 against https://github.com/jkbr/rrule.git#2.1.0
bower angular-animate#1.5.0              cached https://github.com/angular/bower-angular-animate.git#1.5.0
bower angular-animate#1.5.0            validate 1.5.0 against https://github.com/angular/bower-angular-animate.git#1.5.0
bower angular-translate-loader-static-files#2.11.0           cached https://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.11.0
bower angular-translate-loader-static-files#2.11.0         validate 2.11.0 against https://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.11.0
bower angular-dynamic-locale#0.1.*                           cached https://github.com/lgalfaso/angular-dynamic-locale.git#0.1.36
bower angular-dynamic-locale#0.1.*                         validate 0.1.36 against https://github.com/lgalfaso/angular-dynamic-locale.git#0.1.*
bower skycons#*                                            download https://github.com/darkskyapp/skycons/archive/master.tar.gz
bower angular#>=1.2.26 <1.6                                  cached https://github.com/angular/bower-angular.git#1.5.11
bower angular#>=1.2.26 <1.6                                validate 1.5.11 against https://github.com/angular/bower-angular.git#>=1.2.26 <1.6
bower skycons#*                                             extract archive.tar.gz
bower skycons#*                                            resolved https://github.com/darkskyapp/skycons.git#41ff933289
bower angular#1.5.0                                          cached https://github.com/angular/bower-angular.git#1.5.0
bower angular#1.5.0                                        validate 1.5.0 against https://github.com/angular/bower-angular.git#1.5.0
bower angular-translate#2.11.0                              install angular-translate#2.11.0
bower moment#2.10.6                                         install moment#2.10.6
bower angular-i18n#1.5.0                                    install angular-i18n#1.5.0
bower angular#1.5.0                                         install angular#1.5.0
bower rrule#2.1.0                                           install rrule#2.1.0
bower angular-translate-loader-static-files#2.11.0          install angular-translate-loader-static-files#2.11.0
bower angular-dynamic-locale#0.1.*                          install angular-dynamic-locale#0.1.36
bower skycons#*                                             install skycons#41ff933289
bower angular-animate#1.5.0                                 install angular-animate#1.5.0
bower                                                   postinstall npm run wiredep
bower                                                   postinstall > smart-mirror@0.0.17 wiredep /home/eusiddiq/smart-mirror
bower                                                   postinstall > wiredep -s index.html

angular-translate#2.11.0 bower_components/angular-translate
└── angular#1.5.0

moment#2.10.6 bower_components/moment

angular-i18n#1.5.0 bower_components/angular-i18n

angular#1.5.0 bower_components/angular

rrule#2.1.0 bower_components/rrule

angular-translate-loader-static-files#2.11.0 bower_components/angular-translate-loader-static-files
└── angular-translate#2.11.0

angular-dynamic-locale#0.1.36 bower_components/angular-dynamic-locale

skycons#41ff933289 bower_components/skycons

angular-animate#1.5.0 bower_components/angular-animate
└── angular#1.5.0
npm notice created a lockfile as package-lock.json. You should commit this file.
added 534 packages in 183.628s
```
The debug log is so vague I am not able to figure out what is wrong, any ideas on what I can do?

**Comment by evancohen** [comment]
This **should** be fixed as of `v0.0.19`. If not please comment and I'll try to sort it out.
