### ISSUE TITLE
sonus error

### ISSUE THREAD

**Issue by yyeong** [evancohen/smart-mirror#753]
**There is an error. :(**

pi@raspberrypi:~/smart-mirror $ npm start

> smart-mirror@0.0.18 start /home/pi/smart-mirror
> electron main.js 

Remote listening on http://192.168.0.23:8080
ERROR e/pi/smart-mirror/node_modules/grpc/src/grpc_extension.js:57
    throw e;
    ^

Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/smart-mirror/node_modules/grpc/src/node/extension_binary/node-v48-linux-arm-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/smart-mirror/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)

Relaunching...

**and**

pi@raspberrypi:~/smart-mirror $ npm run sonus

> smart-mirror@0.0.18 sonus /home/pi/smart-mirror
> node sonus.js

/home/pi/smart-mirror/node_modules/grpc/src/grpc_extension.js:57
    throw e;
    ^

Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/smart-mirror/node_modules/grpc/src/node/extension_binary/node-v48-linux-arm-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/smart-mirror/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smart-mirror@0.0.18 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.18 sonus script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-09-29T06_50_35_192Z-debug.log

**plz help.... What can I do???**

**Comment by evancohen** [comment]
Can you try the solution on #755?

**Comment by evancohen** [comment]
Good news: This is now fixed in `v0.0.19`, see: #763
