### ISSUE TITLE
UnhanledPromiseRejectionWarning Problem...while speechRecognition

### ISSUE THREAD

**Issue by jinseok-p** [evancohen/smart-mirror#758]
Hi, i`m making smart-mirror for my own and there`s some problems...
( environment : rasp 3 / rasbian,  npm -v : 3.10.10,  node -v : v6.10.1 )

when i ran smart-mirror..

Remote listening on http://192.168.100.111:8080
ERROR e:3526) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: The incoming JSON object does not contain a client_email field

occurs..
i installed every thing according to your docs. and i enabled billing and etc.
And i checked my keyfile.json, service_account json file too but i think there`s nothing wrong with it.

help me to solve it :(

**Comment by jinseok-p** [comment]
still error..
it`s already updated.

Here`s my sonus.js
i changed 'const speech' and made 'const client'. Any problem here?

'use strict'
// Load in smart mirror config
const os = require('os');
const fs = require('fs');
const path = require('path')

let config
try {
	config = require("./config.json")
} catch (e) {
	config = false
}

if (!config || !config.speech || !config.speech.keyFilename || !config.speech.hotwords || !config.general.language) {
	throw "Configuration Error! See: https://docs.smart-mirror.io/docs/configure_the_mirror.html#speech"
}

var keyFile = JSON.parse(fs.readFileSync(path.resolve(config.speech.keyFilename), "utf8"))
// Configure Sonus
const Sonus = require('sonus')
const speech = require('@google-cloud/speech')
const client = new speech.SpeechClient({
	projectId: keyFile.project_id,
	keyFilename: config.speech.keyFilename
})
// Hotword helpers
let sensitivity = config.speech.sensitivity || '0.5'
let hotwords = []
let addHotword = function (modelFile, hotword, sensitivity) {
	let file = path.resolve(modelFile)
	if (fs.existsSync(file)) {
		hotwords.push({ file, hotword, sensitivity })
	} else {
		console.log('Model: "', file, '" not found.')
	}
}

for (let i = 0; i < config.speech.hotwords.length; i++) {
	addHotword(config.speech.hotwords[i].model, config.speech.hotwords[i].keyword, sensitivity)
}


const language = config.general.language
const recordProgram = (os.arch() == 'arm') ? "arecord" : "rec"
const device = (config.speech.device != "") ? config.speech.device : 'default'
const sonus = Sonus.init({ hotwords, language, recordProgram, device }, client)

// Start Recognition
Sonus.start(sonus)

// Event IPC
sonus.on('hotword', (index) => console.log("!h:", index))
sonus.on('partial-result', result => console.log("!p:", result))
sonus.on('final-result', result => console.log("!f:", result))
sonus.on('error', error => console.error("!e:", error))

**Comment by jinseok-p** [comment]
Finally, my mirror recognize "smart mirror" sound ( I`ve got " !h: 1 " response! )
But still appears error....

> smart-mirror@0.0.18 sonus /home/pi/smart-mirror
> node sonus.js

(node:1933) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: The incoming JSON object does not contain a client_email field
(node:1933) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: The incoming JSON object does not contain a client_email field
(node:1933) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: The incoming JSON object does not contain a client_email field
(node:1933) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: The incoming JSON object does not contain a client_email field
(node:1933) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: The incoming JSON object does not contain a client_email field
(node:1933) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: The incoming JSON object does not contain a client_email field
(node:1933) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: The incoming JSON object does not contain a client_email field
!h: 1
(node:1933) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 7)
!e: { streamingError: 
   Error: The incoming JSON object does not contain a client_email field
       at JWT.fromJSON (/home/pi/smart-mirror/node_modules/google-auth-library/build/src/auth/jwtclient.js:180:19)
       at GoogleAuth.fromJSON (/home/pi/smart-mirror/node_modules/google-auth-library/build/src/auth/googleauth.js:313:16)
       at ReadStream.inputStream.setEncoding.on.on.on.err (/home/pi/smart-mirror/node_modules/google-auth-library/build/src/auth/googleauth.js:344:36)
       at emitNone (events.js:91:20)
       at ReadStream.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9) }

**Comment by jinseok-p** [comment]
i found the problem ! there`s a mistake about keyfile while typed thru Remote UI!
i solve it, thanks!
