### ISSUE TITLE
cannot get new Soundcloud  api key

### ISSUE THREAD

**Issue by JOJOYJ** [evancohen/smart-mirror#815]
https://github.com/embian-inc/smart-mirror-ko 

I'd like to look at this and overwrite it in the mirror of EvanCohen.
This man made  two or three years ago based on Ivan Cohen's mirror.
This problem arose when I overwritten it.
Can we use this?

> smart-mirror@0.0.1 start /home/pi/smart-mirror
> electron main.js

App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/smart-mirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/smart-mirror/main.js:3:11)
    at Object.<anonymous> (/home/pi/smart-mirror/main.js:70:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'app'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/smart-mirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/smart-mirror/main.js:3:11)
    at Object.<anonymous> (/home/pi/smart-mirror/main.js:70:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)

**Comment by sdetweil** [comment]
did u finish the install?  
npm install

the soundcloud and subway services are all that are missing compared to back then.

you can use my sample plugin to move those capabilities into the latest version. 
https://github.com/sdetweil/samplePlugin

**Comment by JOJOYJ** [comment]
Is  SoundCloud not possible with evan cohen smart mirrors at this time?

**Comment by sdetweil** [comment]
soundcloud is not giving out api keys 

see https://docs.google.com/forms/d/e/1FAIpQLSfNxc82RJuzC0DnISat7n4H-G7IsPQIdaMpe202iiHZEoso9w/closedform

so, net.. no not available anymore

**Comment by sdetweil** [comment]
dup #85
