### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by bsflutes** [evancohen/smart-mirror#874]
pi@raspberrypi:~/smart-mirror $ npm run sonus
> smart-mirror@0.0.27 sonus /home/pi/smart-mirror
> node sonus.js

/home/pi/smart-mirror/sonus.js:24
	keyFilename: ROOT_DIR +  'keyfile.json'
	             ^

ReferenceError: ROOT_DIR is not defined
    at Object.<anonymous> (/home/pi/smart-mirror/sonus.js:24:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smart-mirror@0.0.27 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.27 sonus script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-09-11T04_07_01_509Z-debug.log

**Comment by sdetweil** [comment]
>> keyFilename: ROOT_DIR + 'keyfile.json'
^
that is not the code in the sinus.js file

did u edit the file?

**Comment by sdetweil** [comment]
did u solve this?  I will close if u don't respond

**Comment by sdetweil** [comment]
closed, no response
